apiVersion: v1
kind: Service
metadata:
  name: poc-starlingx
  labels:
    app: poc-starlingx
spec:
  type: NodePort
  ports:
  - port: 8100
    targetPort: 8000
    nodePort: 31234
  selector:
    app: poc-starlingx